/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:ec76e4eb-dc6c-4324-8eab-312d7e5c1a41",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_6our1ZtsR",
    "aws_user_pools_web_client_id": "6cap1n2gv32h5vhla8dqm1njt7",
    "oauth": {
        "domain": "petingdatesc1a79563-c1a79563-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://8u-s5r.kozarip.peting.exp.direct:80/--/,exp://127.0.0.1:19000/--/,exp://127.0.0.1:19000/--/,peting://,exp://exp.host/@kozarip/peting/",
        "redirectSignOut": "exp://exp.host/@kozarip/peting/,exp://exp.host/@kozarip/peting/,peting://,exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://crwpmoua3bdjtgdlrsh4kbqss4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4sjeimaplfdldmxuor4xqeafgu",
    "aws_user_files_s3_bucket": "petingdatesa24bb58985164c809faa1948c109ca8394042-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
